title: "State of the ARG"
description: "An online seminar series on ancestral recombination graphs."
url: "https://yundeng98.github.io"
baseurl: "/State-of-the-ARG"
repository: "YunDeng98/State-of-the-ARG"

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dark"

search: false
markdown: kramdown

plugins:
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
